// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package application

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/emrserverless"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/emrserverless/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/emrserverless-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Application{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetApplicationOutput
	resp, err = rm.sdkapi.GetApplication(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetApplication", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.Application.ApplicationId != nil {
		ko.Status.ID = resp.Application.ApplicationId
	} else {
		ko.Status.ID = nil
	}
	if resp.Application.Architecture != "" {
		ko.Spec.Architecture = aws.String(string(resp.Application.Architecture))
	} else {
		ko.Spec.Architecture = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Application.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Application.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Application.AutoStartConfiguration != nil {
		f3 := &svcapitypes.AutoStartConfig{}
		if resp.Application.AutoStartConfiguration.Enabled != nil {
			f3.Enabled = resp.Application.AutoStartConfiguration.Enabled
		}
		ko.Spec.AutoStartConfiguration = f3
	} else {
		ko.Spec.AutoStartConfiguration = nil
	}
	if resp.Application.AutoStopConfiguration != nil {
		f4 := &svcapitypes.AutoStopConfig{}
		if resp.Application.AutoStopConfiguration.Enabled != nil {
			f4.Enabled = resp.Application.AutoStopConfiguration.Enabled
		}
		if resp.Application.AutoStopConfiguration.IdleTimeoutMinutes != nil {
			idleTimeoutMinutesCopy := int64(*resp.Application.AutoStopConfiguration.IdleTimeoutMinutes)
			f4.IdleTimeoutMinutes = &idleTimeoutMinutesCopy
		}
		ko.Spec.AutoStopConfiguration = f4
	} else {
		ko.Spec.AutoStopConfiguration = nil
	}
	if resp.Application.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Application.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Application.DiskEncryptionConfiguration != nil {
		f6 := &svcapitypes.DiskEncryptionConfiguration{}
		if resp.Application.DiskEncryptionConfiguration.EncryptionContext != nil {
			f6.EncryptionContext = aws.StringMap(resp.Application.DiskEncryptionConfiguration.EncryptionContext)
		}
		if resp.Application.DiskEncryptionConfiguration.EncryptionKeyArn != nil {
			f6.EncryptionKeyARN = resp.Application.DiskEncryptionConfiguration.EncryptionKeyArn
		}
		ko.Spec.DiskEncryptionConfiguration = f6
	} else {
		ko.Spec.DiskEncryptionConfiguration = nil
	}
	if resp.Application.IdentityCenterConfiguration != nil {
		f7 := &svcapitypes.IdentityCenterConfigurationInput{}
		if resp.Application.IdentityCenterConfiguration.IdentityCenterInstanceArn != nil {
			f7.IdentityCenterInstanceARN = resp.Application.IdentityCenterConfiguration.IdentityCenterInstanceArn
		}
		if resp.Application.IdentityCenterConfiguration.UserBackgroundSessionsEnabled != nil {
			f7.UserBackgroundSessionsEnabled = resp.Application.IdentityCenterConfiguration.UserBackgroundSessionsEnabled
		}
		ko.Spec.IdentityCenterConfiguration = f7
	} else {
		ko.Spec.IdentityCenterConfiguration = nil
	}
	if resp.Application.ImageConfiguration != nil {
		f8 := &svcapitypes.ImageConfigurationInput{}
		if resp.Application.ImageConfiguration.ImageUri != nil {
			f8.ImageURI = resp.Application.ImageConfiguration.ImageUri
		}
		ko.Spec.ImageConfiguration = f8
	} else {
		ko.Spec.ImageConfiguration = nil
	}
	if resp.Application.InitialCapacity != nil {
		f9 := map[string]*svcapitypes.InitialCapacityConfig{}
		for f9key, f9valiter := range resp.Application.InitialCapacity {
			f9val := &svcapitypes.InitialCapacityConfig{}
			if f9valiter.WorkerConfiguration != nil {
				f9valf0 := &svcapitypes.WorkerResourceConfig{}
				if f9valiter.WorkerConfiguration.Cpu != nil {
					f9valf0.CPU = f9valiter.WorkerConfiguration.Cpu
				}
				if f9valiter.WorkerConfiguration.Disk != nil {
					f9valf0.Disk = f9valiter.WorkerConfiguration.Disk
				}
				if f9valiter.WorkerConfiguration.DiskType != nil {
					f9valf0.DiskType = f9valiter.WorkerConfiguration.DiskType
				}
				if f9valiter.WorkerConfiguration.Memory != nil {
					f9valf0.Memory = f9valiter.WorkerConfiguration.Memory
				}
				f9val.WorkerConfiguration = f9valf0
			}
			if f9valiter.WorkerCount != nil {
				f9val.WorkerCount = f9valiter.WorkerCount
			}
			f9[f9key] = f9val
		}
		ko.Spec.InitialCapacity = f9
	} else {
		ko.Spec.InitialCapacity = nil
	}
	if resp.Application.InteractiveConfiguration != nil {
		f10 := &svcapitypes.InteractiveConfiguration{}
		if resp.Application.InteractiveConfiguration.LivyEndpointEnabled != nil {
			f10.LivyEndpointEnabled = resp.Application.InteractiveConfiguration.LivyEndpointEnabled
		}
		if resp.Application.InteractiveConfiguration.StudioEnabled != nil {
			f10.StudioEnabled = resp.Application.InteractiveConfiguration.StudioEnabled
		}
		ko.Spec.InteractiveConfiguration = f10
	} else {
		ko.Spec.InteractiveConfiguration = nil
	}
	if resp.Application.JobLevelCostAllocationConfiguration != nil {
		f11 := &svcapitypes.JobLevelCostAllocationConfiguration{}
		if resp.Application.JobLevelCostAllocationConfiguration.Enabled != nil {
			f11.Enabled = resp.Application.JobLevelCostAllocationConfiguration.Enabled
		}
		ko.Spec.JobLevelCostAllocationConfiguration = f11
	} else {
		ko.Spec.JobLevelCostAllocationConfiguration = nil
	}
	if resp.Application.MaximumCapacity != nil {
		f12 := &svcapitypes.MaximumAllowedResources{}
		if resp.Application.MaximumCapacity.Cpu != nil {
			f12.CPU = resp.Application.MaximumCapacity.Cpu
		}
		if resp.Application.MaximumCapacity.Disk != nil {
			f12.Disk = resp.Application.MaximumCapacity.Disk
		}
		if resp.Application.MaximumCapacity.Memory != nil {
			f12.Memory = resp.Application.MaximumCapacity.Memory
		}
		ko.Spec.MaximumCapacity = f12
	} else {
		ko.Spec.MaximumCapacity = nil
	}
	if resp.Application.MonitoringConfiguration != nil {
		f13 := &svcapitypes.MonitoringConfiguration{}
		if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration != nil {
			f13f0 := &svcapitypes.CloudWatchLoggingConfiguration{}
			if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled != nil {
				f13f0.Enabled = resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled
			}
			if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyArn != nil {
				f13f0.EncryptionKeyARN = resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyArn
			}
			if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName != nil {
				f13f0.LogGroupName = resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName
			}
			if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix != nil {
				f13f0.LogStreamNamePrefix = resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix
			}
			if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes != nil {
				f13f0f4 := map[string][]*string{}
				for f13f0f4key, f13f0f4valiter := range resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes {
					f13f0f4[f13f0f4key] = aws.StringSlice(f13f0f4valiter)
				}
				f13f0.LogTypes = f13f0f4
			}
			f13.CloudWatchLoggingConfiguration = f13f0
		}
		if resp.Application.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration != nil {
			f13f1 := &svcapitypes.ManagedPersistenceMonitoringConfiguration{}
			if resp.Application.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled != nil {
				f13f1.Enabled = resp.Application.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled
			}
			if resp.Application.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyArn != nil {
				f13f1.EncryptionKeyARN = resp.Application.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyArn
			}
			f13.ManagedPersistenceMonitoringConfiguration = f13f1
		}
		if resp.Application.MonitoringConfiguration.PrometheusMonitoringConfiguration != nil {
			f13f2 := &svcapitypes.PrometheusMonitoringConfiguration{}
			if resp.Application.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteUrl != nil {
				f13f2.RemoteWriteURL = resp.Application.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteUrl
			}
			f13.PrometheusMonitoringConfiguration = f13f2
		}
		if resp.Application.MonitoringConfiguration.S3MonitoringConfiguration != nil {
			f13f3 := &svcapitypes.S3MonitoringConfiguration{}
			if resp.Application.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyArn != nil {
				f13f3.EncryptionKeyARN = resp.Application.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyArn
			}
			if resp.Application.MonitoringConfiguration.S3MonitoringConfiguration.LogUri != nil {
				f13f3.LogURI = resp.Application.MonitoringConfiguration.S3MonitoringConfiguration.LogUri
			}
			f13.S3MonitoringConfiguration = f13f3
		}
		ko.Spec.MonitoringConfiguration = f13
	} else {
		ko.Spec.MonitoringConfiguration = nil
	}
	if resp.Application.Name != nil {
		ko.Spec.Name = resp.Application.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Application.NetworkConfiguration != nil {
		f15 := &svcapitypes.NetworkConfiguration{}
		if resp.Application.NetworkConfiguration.SecurityGroupIds != nil {
			f15.SecurityGroupIDs = aws.StringSlice(resp.Application.NetworkConfiguration.SecurityGroupIds)
		}
		if resp.Application.NetworkConfiguration.SubnetIds != nil {
			f15.SubnetIDs = aws.StringSlice(resp.Application.NetworkConfiguration.SubnetIds)
		}
		ko.Spec.NetworkConfiguration = f15
	} else {
		ko.Spec.NetworkConfiguration = nil
	}
	if resp.Application.ReleaseLabel != nil {
		ko.Spec.ReleaseLabel = resp.Application.ReleaseLabel
	} else {
		ko.Spec.ReleaseLabel = nil
	}
	if resp.Application.RuntimeConfiguration != nil {
		f17 := []*svcapitypes.Configuration{}
		for _, f17iter := range resp.Application.RuntimeConfiguration {
			f17elem := &svcapitypes.Configuration{}
			if f17iter.Classification != nil {
				f17elem.Classification = f17iter.Classification
			}
			if f17iter.Properties != nil {
				f17elem.Properties = aws.StringMap(f17iter.Properties)
			}
			f17 = append(f17, f17elem)
		}
		ko.Spec.RuntimeConfiguration = f17
	} else {
		ko.Spec.RuntimeConfiguration = nil
	}
	if resp.Application.SchedulerConfiguration != nil {
		f18 := &svcapitypes.SchedulerConfiguration{}
		if resp.Application.SchedulerConfiguration.MaxConcurrentRuns != nil {
			maxConcurrentRunsCopy := int64(*resp.Application.SchedulerConfiguration.MaxConcurrentRuns)
			f18.MaxConcurrentRuns = &maxConcurrentRunsCopy
		}
		if resp.Application.SchedulerConfiguration.QueueTimeoutMinutes != nil {
			queueTimeoutMinutesCopy := int64(*resp.Application.SchedulerConfiguration.QueueTimeoutMinutes)
			f18.QueueTimeoutMinutes = &queueTimeoutMinutesCopy
		}
		ko.Spec.SchedulerConfiguration = f18
	} else {
		ko.Spec.SchedulerConfiguration = nil
	}
	if resp.Application.State != "" {
		ko.Status.State = aws.String(string(resp.Application.State))
	} else {
		ko.Status.State = nil
	}
	if resp.Application.StateDetails != nil {
		ko.Status.StateDetails = resp.Application.StateDetails
	} else {
		ko.Status.StateDetails = nil
	}
	if resp.Application.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.Application.Tags)
	} else {
		ko.Spec.Tags = nil
	}
	if resp.Application.Type != nil {
		ko.Spec.Type = resp.Application.Type
	} else {
		ko.Spec.Type = nil
	}
	if resp.Application.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.Application.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}
	if resp.Application.WorkerTypeSpecifications != nil {
		f24 := map[string]*svcapitypes.WorkerTypeSpecification{}
		for f24key, f24valiter := range resp.Application.WorkerTypeSpecifications {
			f24val := &svcapitypes.WorkerTypeSpecification{}
			if f24valiter.ImageConfiguration != nil {
				f24valf0 := &svcapitypes.ImageConfiguration{}
				if f24valiter.ImageConfiguration.ImageUri != nil {
					f24valf0.ImageURI = f24valiter.ImageConfiguration.ImageUri
				}
				if f24valiter.ImageConfiguration.ResolvedImageDigest != nil {
					f24valf0.ResolvedImageDigest = f24valiter.ImageConfiguration.ResolvedImageDigest
				}
				f24val.ImageConfiguration = f24valf0
			}
			f24[f24key] = f24val
		}
		ko.Spec.WorkerTypeSpecifications = f24
	} else {
		ko.Spec.WorkerTypeSpecifications = nil
	}

	rm.setStatusDefaults(ko)
	// The EMR Serverless GetApplication API continues to return deleted
	// applications with their state set to TERMINATED rather than returning
	// a NotFound error.
	//
	// Treating TERMINATED as NotFound allows the reconciler to proceed with
	// Create if user deletes application externally
	if ko.Status.State != nil && *ko.Status.State == string(svcapitypes.ApplicationState_TERMINATED) {
		return nil, ackerr.NotFound
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetApplicationInput, error) {
	res := &svcsdk.GetApplicationInput{}

	if r.ko.Status.ID != nil {
		res.ApplicationId = r.ko.Status.ID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateApplicationOutput
	_ = resp
	resp, err = rm.sdkapi.CreateApplication(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateApplication", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ApplicationId != nil {
		ko.Status.ID = resp.ApplicationId
	} else {
		ko.Status.ID = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateApplicationInput, error) {
	res := &svcsdk.CreateApplicationInput{}

	if r.ko.Spec.Architecture != nil {
		res.Architecture = svcsdktypes.Architecture(*r.ko.Spec.Architecture)
	}
	if r.ko.Spec.AutoStartConfiguration != nil {
		f1 := &svcsdktypes.AutoStartConfig{}
		if r.ko.Spec.AutoStartConfiguration.Enabled != nil {
			f1.Enabled = r.ko.Spec.AutoStartConfiguration.Enabled
		}
		res.AutoStartConfiguration = f1
	}
	if r.ko.Spec.AutoStopConfiguration != nil {
		f2 := &svcsdktypes.AutoStopConfig{}
		if r.ko.Spec.AutoStopConfiguration.Enabled != nil {
			f2.Enabled = r.ko.Spec.AutoStopConfiguration.Enabled
		}
		if r.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes != nil {
			idleTimeoutMinutesCopy0 := *r.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes
			if idleTimeoutMinutesCopy0 > math.MaxInt32 || idleTimeoutMinutesCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field idleTimeoutMinutes is of type int32")
			}
			idleTimeoutMinutesCopy := int32(idleTimeoutMinutesCopy0)
			f2.IdleTimeoutMinutes = &idleTimeoutMinutesCopy
		}
		res.AutoStopConfiguration = f2
	}
	if r.ko.Spec.DiskEncryptionConfiguration != nil {
		f4 := &svcsdktypes.DiskEncryptionConfiguration{}
		if r.ko.Spec.DiskEncryptionConfiguration.EncryptionContext != nil {
			f4.EncryptionContext = aws.ToStringMap(r.ko.Spec.DiskEncryptionConfiguration.EncryptionContext)
		}
		if r.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN != nil {
			f4.EncryptionKeyArn = r.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN
		}
		res.DiskEncryptionConfiguration = f4
	}
	if r.ko.Spec.IdentityCenterConfiguration != nil {
		f5 := &svcsdktypes.IdentityCenterConfigurationInput{}
		if r.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN != nil {
			f5.IdentityCenterInstanceArn = r.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN
		}
		if r.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled != nil {
			f5.UserBackgroundSessionsEnabled = r.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled
		}
		res.IdentityCenterConfiguration = f5
	}
	if r.ko.Spec.ImageConfiguration != nil {
		f6 := &svcsdktypes.ImageConfigurationInput{}
		if r.ko.Spec.ImageConfiguration.ImageURI != nil {
			f6.ImageUri = r.ko.Spec.ImageConfiguration.ImageURI
		}
		res.ImageConfiguration = f6
	}
	if r.ko.Spec.InitialCapacity != nil {
		f7 := map[string]svcsdktypes.InitialCapacityConfig{}
		for f7key, f7valiter := range r.ko.Spec.InitialCapacity {
			f7val := &svcsdktypes.InitialCapacityConfig{}
			if f7valiter.WorkerConfiguration != nil {
				f7valf0 := &svcsdktypes.WorkerResourceConfig{}
				if f7valiter.WorkerConfiguration.CPU != nil {
					f7valf0.Cpu = f7valiter.WorkerConfiguration.CPU
				}
				if f7valiter.WorkerConfiguration.Disk != nil {
					f7valf0.Disk = f7valiter.WorkerConfiguration.Disk
				}
				if f7valiter.WorkerConfiguration.DiskType != nil {
					f7valf0.DiskType = f7valiter.WorkerConfiguration.DiskType
				}
				if f7valiter.WorkerConfiguration.Memory != nil {
					f7valf0.Memory = f7valiter.WorkerConfiguration.Memory
				}
				f7val.WorkerConfiguration = f7valf0
			}
			if f7valiter.WorkerCount != nil {
				f7val.WorkerCount = f7valiter.WorkerCount
			}
			f7[f7key] = *f7val
		}
		res.InitialCapacity = f7
	}
	if r.ko.Spec.InteractiveConfiguration != nil {
		f8 := &svcsdktypes.InteractiveConfiguration{}
		if r.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled != nil {
			f8.LivyEndpointEnabled = r.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled
		}
		if r.ko.Spec.InteractiveConfiguration.StudioEnabled != nil {
			f8.StudioEnabled = r.ko.Spec.InteractiveConfiguration.StudioEnabled
		}
		res.InteractiveConfiguration = f8
	}
	if r.ko.Spec.JobLevelCostAllocationConfiguration != nil {
		f9 := &svcsdktypes.JobLevelCostAllocationConfiguration{}
		if r.ko.Spec.JobLevelCostAllocationConfiguration.Enabled != nil {
			f9.Enabled = r.ko.Spec.JobLevelCostAllocationConfiguration.Enabled
		}
		res.JobLevelCostAllocationConfiguration = f9
	}
	if r.ko.Spec.MaximumCapacity != nil {
		f10 := &svcsdktypes.MaximumAllowedResources{}
		if r.ko.Spec.MaximumCapacity.CPU != nil {
			f10.Cpu = r.ko.Spec.MaximumCapacity.CPU
		}
		if r.ko.Spec.MaximumCapacity.Disk != nil {
			f10.Disk = r.ko.Spec.MaximumCapacity.Disk
		}
		if r.ko.Spec.MaximumCapacity.Memory != nil {
			f10.Memory = r.ko.Spec.MaximumCapacity.Memory
		}
		res.MaximumCapacity = f10
	}
	if r.ko.Spec.MonitoringConfiguration != nil {
		f11 := &svcsdktypes.MonitoringConfiguration{}
		if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration != nil {
			f11f0 := &svcsdktypes.CloudWatchLoggingConfiguration{}
			if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled != nil {
				f11f0.Enabled = r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled
			}
			if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN != nil {
				f11f0.EncryptionKeyArn = r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN
			}
			if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName != nil {
				f11f0.LogGroupName = r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName
			}
			if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix != nil {
				f11f0.LogStreamNamePrefix = r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix
			}
			if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes != nil {
				f11f0f4 := map[string][]string{}
				for f11f0f4key, f11f0f4valiter := range r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes {
					f11f0f4[f11f0f4key] = aws.ToStringSlice(f11f0f4valiter)
				}
				f11f0.LogTypes = f11f0f4
			}
			f11.CloudWatchLoggingConfiguration = f11f0
		}
		if r.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration != nil {
			f11f1 := &svcsdktypes.ManagedPersistenceMonitoringConfiguration{}
			if r.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled != nil {
				f11f1.Enabled = r.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled
			}
			if r.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN != nil {
				f11f1.EncryptionKeyArn = r.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN
			}
			f11.ManagedPersistenceMonitoringConfiguration = f11f1
		}
		if r.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration != nil {
			f11f2 := &svcsdktypes.PrometheusMonitoringConfiguration{}
			if r.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL != nil {
				f11f2.RemoteWriteUrl = r.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL
			}
			f11.PrometheusMonitoringConfiguration = f11f2
		}
		if r.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration != nil {
			f11f3 := &svcsdktypes.S3MonitoringConfiguration{}
			if r.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN != nil {
				f11f3.EncryptionKeyArn = r.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN
			}
			if r.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI != nil {
				f11f3.LogUri = r.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI
			}
			f11.S3MonitoringConfiguration = f11f3
		}
		res.MonitoringConfiguration = f11
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.NetworkConfiguration != nil {
		f13 := &svcsdktypes.NetworkConfiguration{}
		if r.ko.Spec.NetworkConfiguration.SecurityGroupIDs != nil {
			f13.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
		}
		if r.ko.Spec.NetworkConfiguration.SubnetIDs != nil {
			f13.SubnetIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SubnetIDs)
		}
		res.NetworkConfiguration = f13
	}
	if r.ko.Spec.ReleaseLabel != nil {
		res.ReleaseLabel = r.ko.Spec.ReleaseLabel
	}
	if r.ko.Spec.RuntimeConfiguration != nil {
		f15 := []svcsdktypes.Configuration{}
		for _, f15iter := range r.ko.Spec.RuntimeConfiguration {
			f15elem := &svcsdktypes.Configuration{}
			if f15iter.Classification != nil {
				f15elem.Classification = f15iter.Classification
			}
			if f15iter.Properties != nil {
				f15elem.Properties = aws.ToStringMap(f15iter.Properties)
			}
			f15 = append(f15, *f15elem)
		}
		res.RuntimeConfiguration = f15
	}
	if r.ko.Spec.SchedulerConfiguration != nil {
		f16 := &svcsdktypes.SchedulerConfiguration{}
		if r.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns != nil {
			maxConcurrentRunsCopy0 := *r.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns
			if maxConcurrentRunsCopy0 > math.MaxInt32 || maxConcurrentRunsCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field maxConcurrentRuns is of type int32")
			}
			maxConcurrentRunsCopy := int32(maxConcurrentRunsCopy0)
			f16.MaxConcurrentRuns = &maxConcurrentRunsCopy
		}
		if r.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes != nil {
			queueTimeoutMinutesCopy0 := *r.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes
			if queueTimeoutMinutesCopy0 > math.MaxInt32 || queueTimeoutMinutesCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field queueTimeoutMinutes is of type int32")
			}
			queueTimeoutMinutesCopy := int32(queueTimeoutMinutesCopy0)
			f16.QueueTimeoutMinutes = &queueTimeoutMinutesCopy
		}
		res.SchedulerConfiguration = f16
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}
	if r.ko.Spec.Type != nil {
		res.Type = r.ko.Spec.Type
	}
	if r.ko.Spec.WorkerTypeSpecifications != nil {
		f19 := map[string]svcsdktypes.WorkerTypeSpecificationInput{}
		for f19key, f19valiter := range r.ko.Spec.WorkerTypeSpecifications {
			f19val := &svcsdktypes.WorkerTypeSpecificationInput{}
			if f19valiter.ImageConfiguration != nil {
				f19valf0 := &svcsdktypes.ImageConfigurationInput{}
				if f19valiter.ImageConfiguration.ImageURI != nil {
					f19valf0.ImageUri = f19valiter.ImageConfiguration.ImageURI
				}
				f19val.ImageConfiguration = f19valf0
			}
			f19[f19key] = *f19val
		}
		res.WorkerTypeSpecifications = f19
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if !applicationCreatedOrStopped(latest) {
		msg := fmt.Sprintf("application in '%s' state, cannot be modified until 'CREATED' or 'STOPPED'", string(*latest.ko.Status.State))
		ackcondition.SetSynced(latest, corev1.ConditionFalse, &msg, nil)
		return latest, requeueWaitUntilCanModify(latest)
	}
	updatedDesired := desired.DeepCopy()
	updatedDesired.SetStatus(latest)
	if delta.DifferentAt("Spec.Tags") {
		arn := string(*latest.ko.Status.ACKResourceMetadata.ARN)
		err = syncTags(
			ctx,
			desired.ko.Spec.Tags, latest.ko.Spec.Tags,
			&arn, convertToOrderedACKTags, rm.sdkapi, rm.metrics,
		)
		if err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return rm.concreteResource(updatedDesired), nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateApplicationOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateApplication(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateApplication", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.Application.ApplicationId != nil {
		ko.Status.ID = resp.Application.ApplicationId
	} else {
		ko.Status.ID = nil
	}
	if resp.Application.Architecture != "" {
		ko.Spec.Architecture = aws.String(string(resp.Application.Architecture))
	} else {
		ko.Spec.Architecture = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Application.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Application.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Application.AutoStartConfiguration != nil {
		f3 := &svcapitypes.AutoStartConfig{}
		if resp.Application.AutoStartConfiguration.Enabled != nil {
			f3.Enabled = resp.Application.AutoStartConfiguration.Enabled
		}
		ko.Spec.AutoStartConfiguration = f3
	} else {
		ko.Spec.AutoStartConfiguration = nil
	}
	if resp.Application.AutoStopConfiguration != nil {
		f4 := &svcapitypes.AutoStopConfig{}
		if resp.Application.AutoStopConfiguration.Enabled != nil {
			f4.Enabled = resp.Application.AutoStopConfiguration.Enabled
		}
		if resp.Application.AutoStopConfiguration.IdleTimeoutMinutes != nil {
			idleTimeoutMinutesCopy := int64(*resp.Application.AutoStopConfiguration.IdleTimeoutMinutes)
			f4.IdleTimeoutMinutes = &idleTimeoutMinutesCopy
		}
		ko.Spec.AutoStopConfiguration = f4
	} else {
		ko.Spec.AutoStopConfiguration = nil
	}
	if resp.Application.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.Application.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Application.DiskEncryptionConfiguration != nil {
		f6 := &svcapitypes.DiskEncryptionConfiguration{}
		if resp.Application.DiskEncryptionConfiguration.EncryptionContext != nil {
			f6.EncryptionContext = aws.StringMap(resp.Application.DiskEncryptionConfiguration.EncryptionContext)
		}
		if resp.Application.DiskEncryptionConfiguration.EncryptionKeyArn != nil {
			f6.EncryptionKeyARN = resp.Application.DiskEncryptionConfiguration.EncryptionKeyArn
		}
		ko.Spec.DiskEncryptionConfiguration = f6
	} else {
		ko.Spec.DiskEncryptionConfiguration = nil
	}
	if resp.Application.IdentityCenterConfiguration != nil {
		f7 := &svcapitypes.IdentityCenterConfigurationInput{}
		if resp.Application.IdentityCenterConfiguration.IdentityCenterInstanceArn != nil {
			f7.IdentityCenterInstanceARN = resp.Application.IdentityCenterConfiguration.IdentityCenterInstanceArn
		}
		if resp.Application.IdentityCenterConfiguration.UserBackgroundSessionsEnabled != nil {
			f7.UserBackgroundSessionsEnabled = resp.Application.IdentityCenterConfiguration.UserBackgroundSessionsEnabled
		}
		ko.Spec.IdentityCenterConfiguration = f7
	} else {
		ko.Spec.IdentityCenterConfiguration = nil
	}
	if resp.Application.ImageConfiguration != nil {
		f8 := &svcapitypes.ImageConfigurationInput{}
		if resp.Application.ImageConfiguration.ImageUri != nil {
			f8.ImageURI = resp.Application.ImageConfiguration.ImageUri
		}
		ko.Spec.ImageConfiguration = f8
	} else {
		ko.Spec.ImageConfiguration = nil
	}
	if resp.Application.InitialCapacity != nil {
		f9 := map[string]*svcapitypes.InitialCapacityConfig{}
		for f9key, f9valiter := range resp.Application.InitialCapacity {
			f9val := &svcapitypes.InitialCapacityConfig{}
			if f9valiter.WorkerConfiguration != nil {
				f9valf0 := &svcapitypes.WorkerResourceConfig{}
				if f9valiter.WorkerConfiguration.Cpu != nil {
					f9valf0.CPU = f9valiter.WorkerConfiguration.Cpu
				}
				if f9valiter.WorkerConfiguration.Disk != nil {
					f9valf0.Disk = f9valiter.WorkerConfiguration.Disk
				}
				if f9valiter.WorkerConfiguration.DiskType != nil {
					f9valf0.DiskType = f9valiter.WorkerConfiguration.DiskType
				}
				if f9valiter.WorkerConfiguration.Memory != nil {
					f9valf0.Memory = f9valiter.WorkerConfiguration.Memory
				}
				f9val.WorkerConfiguration = f9valf0
			}
			if f9valiter.WorkerCount != nil {
				f9val.WorkerCount = f9valiter.WorkerCount
			}
			f9[f9key] = f9val
		}
		ko.Spec.InitialCapacity = f9
	} else {
		ko.Spec.InitialCapacity = nil
	}
	if resp.Application.InteractiveConfiguration != nil {
		f10 := &svcapitypes.InteractiveConfiguration{}
		if resp.Application.InteractiveConfiguration.LivyEndpointEnabled != nil {
			f10.LivyEndpointEnabled = resp.Application.InteractiveConfiguration.LivyEndpointEnabled
		}
		if resp.Application.InteractiveConfiguration.StudioEnabled != nil {
			f10.StudioEnabled = resp.Application.InteractiveConfiguration.StudioEnabled
		}
		ko.Spec.InteractiveConfiguration = f10
	} else {
		ko.Spec.InteractiveConfiguration = nil
	}
	if resp.Application.JobLevelCostAllocationConfiguration != nil {
		f11 := &svcapitypes.JobLevelCostAllocationConfiguration{}
		if resp.Application.JobLevelCostAllocationConfiguration.Enabled != nil {
			f11.Enabled = resp.Application.JobLevelCostAllocationConfiguration.Enabled
		}
		ko.Spec.JobLevelCostAllocationConfiguration = f11
	} else {
		ko.Spec.JobLevelCostAllocationConfiguration = nil
	}
	if resp.Application.MaximumCapacity != nil {
		f12 := &svcapitypes.MaximumAllowedResources{}
		if resp.Application.MaximumCapacity.Cpu != nil {
			f12.CPU = resp.Application.MaximumCapacity.Cpu
		}
		if resp.Application.MaximumCapacity.Disk != nil {
			f12.Disk = resp.Application.MaximumCapacity.Disk
		}
		if resp.Application.MaximumCapacity.Memory != nil {
			f12.Memory = resp.Application.MaximumCapacity.Memory
		}
		ko.Spec.MaximumCapacity = f12
	} else {
		ko.Spec.MaximumCapacity = nil
	}
	if resp.Application.MonitoringConfiguration != nil {
		f13 := &svcapitypes.MonitoringConfiguration{}
		if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration != nil {
			f13f0 := &svcapitypes.CloudWatchLoggingConfiguration{}
			if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled != nil {
				f13f0.Enabled = resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled
			}
			if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyArn != nil {
				f13f0.EncryptionKeyARN = resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyArn
			}
			if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName != nil {
				f13f0.LogGroupName = resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName
			}
			if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix != nil {
				f13f0.LogStreamNamePrefix = resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix
			}
			if resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes != nil {
				f13f0f4 := map[string][]*string{}
				for f13f0f4key, f13f0f4valiter := range resp.Application.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes {
					f13f0f4[f13f0f4key] = aws.StringSlice(f13f0f4valiter)
				}
				f13f0.LogTypes = f13f0f4
			}
			f13.CloudWatchLoggingConfiguration = f13f0
		}
		if resp.Application.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration != nil {
			f13f1 := &svcapitypes.ManagedPersistenceMonitoringConfiguration{}
			if resp.Application.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled != nil {
				f13f1.Enabled = resp.Application.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled
			}
			if resp.Application.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyArn != nil {
				f13f1.EncryptionKeyARN = resp.Application.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyArn
			}
			f13.ManagedPersistenceMonitoringConfiguration = f13f1
		}
		if resp.Application.MonitoringConfiguration.PrometheusMonitoringConfiguration != nil {
			f13f2 := &svcapitypes.PrometheusMonitoringConfiguration{}
			if resp.Application.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteUrl != nil {
				f13f2.RemoteWriteURL = resp.Application.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteUrl
			}
			f13.PrometheusMonitoringConfiguration = f13f2
		}
		if resp.Application.MonitoringConfiguration.S3MonitoringConfiguration != nil {
			f13f3 := &svcapitypes.S3MonitoringConfiguration{}
			if resp.Application.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyArn != nil {
				f13f3.EncryptionKeyARN = resp.Application.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyArn
			}
			if resp.Application.MonitoringConfiguration.S3MonitoringConfiguration.LogUri != nil {
				f13f3.LogURI = resp.Application.MonitoringConfiguration.S3MonitoringConfiguration.LogUri
			}
			f13.S3MonitoringConfiguration = f13f3
		}
		ko.Spec.MonitoringConfiguration = f13
	} else {
		ko.Spec.MonitoringConfiguration = nil
	}
	if resp.Application.Name != nil {
		ko.Spec.Name = resp.Application.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Application.NetworkConfiguration != nil {
		f15 := &svcapitypes.NetworkConfiguration{}
		if resp.Application.NetworkConfiguration.SecurityGroupIds != nil {
			f15.SecurityGroupIDs = aws.StringSlice(resp.Application.NetworkConfiguration.SecurityGroupIds)
		}
		if resp.Application.NetworkConfiguration.SubnetIds != nil {
			f15.SubnetIDs = aws.StringSlice(resp.Application.NetworkConfiguration.SubnetIds)
		}
		ko.Spec.NetworkConfiguration = f15
	} else {
		ko.Spec.NetworkConfiguration = nil
	}
	if resp.Application.ReleaseLabel != nil {
		ko.Spec.ReleaseLabel = resp.Application.ReleaseLabel
	} else {
		ko.Spec.ReleaseLabel = nil
	}
	if resp.Application.RuntimeConfiguration != nil {
		f17 := []*svcapitypes.Configuration{}
		for _, f17iter := range resp.Application.RuntimeConfiguration {
			f17elem := &svcapitypes.Configuration{}
			if f17iter.Classification != nil {
				f17elem.Classification = f17iter.Classification
			}
			if f17iter.Properties != nil {
				f17elem.Properties = aws.StringMap(f17iter.Properties)
			}
			f17 = append(f17, f17elem)
		}
		ko.Spec.RuntimeConfiguration = f17
	} else {
		ko.Spec.RuntimeConfiguration = nil
	}
	if resp.Application.SchedulerConfiguration != nil {
		f18 := &svcapitypes.SchedulerConfiguration{}
		if resp.Application.SchedulerConfiguration.MaxConcurrentRuns != nil {
			maxConcurrentRunsCopy := int64(*resp.Application.SchedulerConfiguration.MaxConcurrentRuns)
			f18.MaxConcurrentRuns = &maxConcurrentRunsCopy
		}
		if resp.Application.SchedulerConfiguration.QueueTimeoutMinutes != nil {
			queueTimeoutMinutesCopy := int64(*resp.Application.SchedulerConfiguration.QueueTimeoutMinutes)
			f18.QueueTimeoutMinutes = &queueTimeoutMinutesCopy
		}
		ko.Spec.SchedulerConfiguration = f18
	} else {
		ko.Spec.SchedulerConfiguration = nil
	}
	if resp.Application.State != "" {
		ko.Status.State = aws.String(string(resp.Application.State))
	} else {
		ko.Status.State = nil
	}
	if resp.Application.StateDetails != nil {
		ko.Status.StateDetails = resp.Application.StateDetails
	} else {
		ko.Status.StateDetails = nil
	}
	if resp.Application.Type != nil {
		ko.Spec.Type = resp.Application.Type
	} else {
		ko.Spec.Type = nil
	}
	if resp.Application.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.Application.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}
	if resp.Application.WorkerTypeSpecifications != nil {
		f24 := map[string]*svcapitypes.WorkerTypeSpecification{}
		for f24key, f24valiter := range resp.Application.WorkerTypeSpecifications {
			f24val := &svcapitypes.WorkerTypeSpecification{}
			if f24valiter.ImageConfiguration != nil {
				f24valf0 := &svcapitypes.ImageConfiguration{}
				if f24valiter.ImageConfiguration.ImageUri != nil {
					f24valf0.ImageURI = f24valiter.ImageConfiguration.ImageUri
				}
				if f24valiter.ImageConfiguration.ResolvedImageDigest != nil {
					f24valf0.ResolvedImageDigest = f24valiter.ImageConfiguration.ResolvedImageDigest
				}
				f24val.ImageConfiguration = f24valf0
			}
			f24[f24key] = f24val
		}
		ko.Spec.WorkerTypeSpecifications = f24
	} else {
		ko.Spec.WorkerTypeSpecifications = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateApplicationInput, error) {
	res := &svcsdk.UpdateApplicationInput{}

	if r.ko.Status.ID != nil {
		res.ApplicationId = r.ko.Status.ID
	}
	if r.ko.Spec.Architecture != nil {
		res.Architecture = svcsdktypes.Architecture(*r.ko.Spec.Architecture)
	}
	if r.ko.Spec.AutoStartConfiguration != nil {
		f2 := &svcsdktypes.AutoStartConfig{}
		if r.ko.Spec.AutoStartConfiguration.Enabled != nil {
			f2.Enabled = r.ko.Spec.AutoStartConfiguration.Enabled
		}
		res.AutoStartConfiguration = f2
	}
	if r.ko.Spec.AutoStopConfiguration != nil {
		f3 := &svcsdktypes.AutoStopConfig{}
		if r.ko.Spec.AutoStopConfiguration.Enabled != nil {
			f3.Enabled = r.ko.Spec.AutoStopConfiguration.Enabled
		}
		if r.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes != nil {
			idleTimeoutMinutesCopy0 := *r.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes
			if idleTimeoutMinutesCopy0 > math.MaxInt32 || idleTimeoutMinutesCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field idleTimeoutMinutes is of type int32")
			}
			idleTimeoutMinutesCopy := int32(idleTimeoutMinutesCopy0)
			f3.IdleTimeoutMinutes = &idleTimeoutMinutesCopy
		}
		res.AutoStopConfiguration = f3
	}
	if r.ko.Spec.DiskEncryptionConfiguration != nil {
		f5 := &svcsdktypes.DiskEncryptionConfiguration{}
		if r.ko.Spec.DiskEncryptionConfiguration.EncryptionContext != nil {
			f5.EncryptionContext = aws.ToStringMap(r.ko.Spec.DiskEncryptionConfiguration.EncryptionContext)
		}
		if r.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN != nil {
			f5.EncryptionKeyArn = r.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN
		}
		res.DiskEncryptionConfiguration = f5
	}
	if r.ko.Spec.IdentityCenterConfiguration != nil {
		f6 := &svcsdktypes.IdentityCenterConfigurationInput{}
		if r.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN != nil {
			f6.IdentityCenterInstanceArn = r.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN
		}
		if r.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled != nil {
			f6.UserBackgroundSessionsEnabled = r.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled
		}
		res.IdentityCenterConfiguration = f6
	}
	if r.ko.Spec.ImageConfiguration != nil {
		f7 := &svcsdktypes.ImageConfigurationInput{}
		if r.ko.Spec.ImageConfiguration.ImageURI != nil {
			f7.ImageUri = r.ko.Spec.ImageConfiguration.ImageURI
		}
		res.ImageConfiguration = f7
	}
	if r.ko.Spec.InitialCapacity != nil {
		f8 := map[string]svcsdktypes.InitialCapacityConfig{}
		for f8key, f8valiter := range r.ko.Spec.InitialCapacity {
			f8val := &svcsdktypes.InitialCapacityConfig{}
			if f8valiter.WorkerConfiguration != nil {
				f8valf0 := &svcsdktypes.WorkerResourceConfig{}
				if f8valiter.WorkerConfiguration.CPU != nil {
					f8valf0.Cpu = f8valiter.WorkerConfiguration.CPU
				}
				if f8valiter.WorkerConfiguration.Disk != nil {
					f8valf0.Disk = f8valiter.WorkerConfiguration.Disk
				}
				if f8valiter.WorkerConfiguration.DiskType != nil {
					f8valf0.DiskType = f8valiter.WorkerConfiguration.DiskType
				}
				if f8valiter.WorkerConfiguration.Memory != nil {
					f8valf0.Memory = f8valiter.WorkerConfiguration.Memory
				}
				f8val.WorkerConfiguration = f8valf0
			}
			if f8valiter.WorkerCount != nil {
				f8val.WorkerCount = f8valiter.WorkerCount
			}
			f8[f8key] = *f8val
		}
		res.InitialCapacity = f8
	}
	if r.ko.Spec.InteractiveConfiguration != nil {
		f9 := &svcsdktypes.InteractiveConfiguration{}
		if r.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled != nil {
			f9.LivyEndpointEnabled = r.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled
		}
		if r.ko.Spec.InteractiveConfiguration.StudioEnabled != nil {
			f9.StudioEnabled = r.ko.Spec.InteractiveConfiguration.StudioEnabled
		}
		res.InteractiveConfiguration = f9
	}
	if r.ko.Spec.JobLevelCostAllocationConfiguration != nil {
		f10 := &svcsdktypes.JobLevelCostAllocationConfiguration{}
		if r.ko.Spec.JobLevelCostAllocationConfiguration.Enabled != nil {
			f10.Enabled = r.ko.Spec.JobLevelCostAllocationConfiguration.Enabled
		}
		res.JobLevelCostAllocationConfiguration = f10
	}
	if r.ko.Spec.MaximumCapacity != nil {
		f11 := &svcsdktypes.MaximumAllowedResources{}
		if r.ko.Spec.MaximumCapacity.CPU != nil {
			f11.Cpu = r.ko.Spec.MaximumCapacity.CPU
		}
		if r.ko.Spec.MaximumCapacity.Disk != nil {
			f11.Disk = r.ko.Spec.MaximumCapacity.Disk
		}
		if r.ko.Spec.MaximumCapacity.Memory != nil {
			f11.Memory = r.ko.Spec.MaximumCapacity.Memory
		}
		res.MaximumCapacity = f11
	}
	if r.ko.Spec.MonitoringConfiguration != nil {
		f12 := &svcsdktypes.MonitoringConfiguration{}
		if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration != nil {
			f12f0 := &svcsdktypes.CloudWatchLoggingConfiguration{}
			if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled != nil {
				f12f0.Enabled = r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled
			}
			if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN != nil {
				f12f0.EncryptionKeyArn = r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN
			}
			if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName != nil {
				f12f0.LogGroupName = r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName
			}
			if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix != nil {
				f12f0.LogStreamNamePrefix = r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix
			}
			if r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes != nil {
				f12f0f4 := map[string][]string{}
				for f12f0f4key, f12f0f4valiter := range r.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes {
					f12f0f4[f12f0f4key] = aws.ToStringSlice(f12f0f4valiter)
				}
				f12f0.LogTypes = f12f0f4
			}
			f12.CloudWatchLoggingConfiguration = f12f0
		}
		if r.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration != nil {
			f12f1 := &svcsdktypes.ManagedPersistenceMonitoringConfiguration{}
			if r.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled != nil {
				f12f1.Enabled = r.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled
			}
			if r.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN != nil {
				f12f1.EncryptionKeyArn = r.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN
			}
			f12.ManagedPersistenceMonitoringConfiguration = f12f1
		}
		if r.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration != nil {
			f12f2 := &svcsdktypes.PrometheusMonitoringConfiguration{}
			if r.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL != nil {
				f12f2.RemoteWriteUrl = r.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL
			}
			f12.PrometheusMonitoringConfiguration = f12f2
		}
		if r.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration != nil {
			f12f3 := &svcsdktypes.S3MonitoringConfiguration{}
			if r.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN != nil {
				f12f3.EncryptionKeyArn = r.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN
			}
			if r.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI != nil {
				f12f3.LogUri = r.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI
			}
			f12.S3MonitoringConfiguration = f12f3
		}
		res.MonitoringConfiguration = f12
	}
	if r.ko.Spec.NetworkConfiguration != nil {
		f13 := &svcsdktypes.NetworkConfiguration{}
		if r.ko.Spec.NetworkConfiguration.SecurityGroupIDs != nil {
			f13.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
		}
		if r.ko.Spec.NetworkConfiguration.SubnetIDs != nil {
			f13.SubnetIds = aws.ToStringSlice(r.ko.Spec.NetworkConfiguration.SubnetIDs)
		}
		res.NetworkConfiguration = f13
	}
	if r.ko.Spec.ReleaseLabel != nil {
		res.ReleaseLabel = r.ko.Spec.ReleaseLabel
	}
	if r.ko.Spec.RuntimeConfiguration != nil {
		f15 := []svcsdktypes.Configuration{}
		for _, f15iter := range r.ko.Spec.RuntimeConfiguration {
			f15elem := &svcsdktypes.Configuration{}
			if f15iter.Classification != nil {
				f15elem.Classification = f15iter.Classification
			}
			if f15iter.Properties != nil {
				f15elem.Properties = aws.ToStringMap(f15iter.Properties)
			}
			f15 = append(f15, *f15elem)
		}
		res.RuntimeConfiguration = f15
	}
	if r.ko.Spec.SchedulerConfiguration != nil {
		f16 := &svcsdktypes.SchedulerConfiguration{}
		if r.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns != nil {
			maxConcurrentRunsCopy0 := *r.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns
			if maxConcurrentRunsCopy0 > math.MaxInt32 || maxConcurrentRunsCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field maxConcurrentRuns is of type int32")
			}
			maxConcurrentRunsCopy := int32(maxConcurrentRunsCopy0)
			f16.MaxConcurrentRuns = &maxConcurrentRunsCopy
		}
		if r.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes != nil {
			queueTimeoutMinutesCopy0 := *r.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes
			if queueTimeoutMinutesCopy0 > math.MaxInt32 || queueTimeoutMinutesCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field queueTimeoutMinutes is of type int32")
			}
			queueTimeoutMinutesCopy := int32(queueTimeoutMinutesCopy0)
			f16.QueueTimeoutMinutes = &queueTimeoutMinutesCopy
		}
		res.SchedulerConfiguration = f16
	}
	if r.ko.Spec.WorkerTypeSpecifications != nil {
		f17 := map[string]svcsdktypes.WorkerTypeSpecificationInput{}
		for f17key, f17valiter := range r.ko.Spec.WorkerTypeSpecifications {
			f17val := &svcsdktypes.WorkerTypeSpecificationInput{}
			if f17valiter.ImageConfiguration != nil {
				f17valf0 := &svcsdktypes.ImageConfigurationInput{}
				if f17valiter.ImageConfiguration.ImageURI != nil {
					f17valf0.ImageUri = f17valiter.ImageConfiguration.ImageURI
				}
				f17val.ImageConfiguration = f17valf0
			}
			f17[f17key] = *f17val
		}
		res.WorkerTypeSpecifications = f17
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteApplicationOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteApplication(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteApplication", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteApplicationInput, error) {
	res := &svcsdk.DeleteApplicationInput{}

	if r.ko.Status.ID != nil {
		res.ApplicationId = r.ko.Status.ID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Application,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException":
		return true
	default:
		return false
	}
}
